Add a command type
fox-it/flow.record pull request #118
Opened 2024-04-15 09:19 UTC by Miauwkeru

This command type splits an executable from its arguments.
It performs some part of detection for windows type paths on a best effort basis.
This is because windows executables handles its own argument parsing

2024-04-15 10:42 UTC, Schamper requested changes

2024-04-15 10:42 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +from typing import Any, List, Optional, Tuple
```suggestion
from typing import Any, Optional
```
Can you change the instances of `List` to `list` and `Tuple` to `tuple`?

2024-04-15 15:42 UTC, Schamper requested changes

2024-04-15 15:42 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +        return "(executable={d.executable!r}, args={d.args})".format(d=self)
```suggestion
        return f"(executable={self.executable!r}, args={self.args})"
```
?

2024-04-15 15:42 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +        windows = value.startswith(("\\", "\\?", "%")) or value.lstrip("\"'")[1] == ":"
Can you add some comments on what this does?

2024-04-16 11:59 UTC, cecinestpasunepipe requested changes

2024-04-16 11:59 UTC, cecinestpasunepipe commented on tests/test_fieldtypes.py
> +def test_command_record():
```suggestion
def test_command_record() -> None:
```

2024-04-16 11:59 UTC, cecinestpasunepipe commented on tests/test_fieldtypes.py
> +def test_command(command_string, expected_executable, expected_argument):
```suggestion
def test_command(command_string: str, expected_executable: str, expected_argument: list[str]) -> None:
```

2024-04-16 11:59 UTC, cecinestpasunepipe commented on tests/test_fieldtypes.py
> +def test_command_integration(tmp_path):
```suggestion
def test_command_integration(tmp_path:Path) -> None:
```

2024-04-16 11:59 UTC, cecinestpasunepipe commented on tests/test_fieldtypes.py
> +        ("windows.exe something,or,somethingelse", "windows.exe", ["something,or,somethingelse"]),
For each line, please state what you test here, i.e. "Can we parse a regular windows command with arguments?".
I also miss a a test for a command without arguments and a test for an illegal value (not the happy-flow).

2024-04-19 13:17 UTC, Schamper requested changes

2024-04-19 13:17 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +        command_type = PATH_WINDOWS if isinstance(self, windows_command) else PATH_POSIX
Maybe rename `PATH_` to something else if you're going to re-use it. `TYPE_` maybe?

2024-04-19 13:17 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +    def __repr__(self):
```suggestion
    def __repr__(self) -> str:
```
Can you also move it under `__init__`.

2024-04-19 14:29 UTC, Schamper requested changes

2024-04-19 14:29 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +    def __repr__(self):
```suggestion
    def __repr__(self) -> str:
```

2024-04-19 14:29 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +    def _pack(self):
Missing return type

2024-04-19 14:29 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +    def from_posix(cls, value: str):
Missing return type

2024-04-19 14:29 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +    def from_windows(cls, value: str):
Missing return type

2024-04-22 15:25 UTC, cecinestpasunepipe submitted a review, later dismissed

2024-04-29 08:17 UTC, Schamper requested changes

2024-04-29 08:17 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +    def __init__(self, value: str | tuple):
Tuple of?

2024-04-29 08:17 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +        self.executable, self.args = self._split_function(value)
Maybe better to swap this around? `if isinstance(value, str)` and fall through for the tuple? That way it can also work for a list.

2024-04-29 08:17 UTC, Schamper commented on flow/record/fieldtypes/__init__.py
> +        if not isinstance(other, command):
Would it be nice to allow comparison against tuple, list and str as well? Makes comparing in selectors a billion times easier.

2024-05-03 10:57 UTC, Schamper approved these changes

2024-05-03 11:10 UTC, merged