Fix ValueError: I/O operation on closed file
fox-it/flow.record pull request #123
Opened 2024-05-08 09:04 UTC by yunzheng

2024-05-08 09:20 UTC, yunzheng commented
This sadly didn't fix the issue :(

Will leave this PR in Draft state for more adhoc tests.

2024-05-17 13:00 UTC, yunzheng commented
Took a while but this should now be fixed. I took quite a deep dive into the pytest internals to figure out the cause.

It's mainly caused due to pytest's capture.py swapping `sys.stdout` with it's own objects, however in our own code we check if the file object is `sys.stdout` or `sys.stdout.buffer`, but as `sys.stdout` keeps getting swapped multiple times (eg: nested pytest operations/fixtures) it could be that a file object that is originally stdout is now not seen as stdout anymore, and therefore closed by `flow.record` internals at certains points.

2024-05-17 13:08 UTC, Schamper requested changes

2024-05-17 13:08 UTC, Schamper commented on flow/record/utils.py
> +        binary: Whether to return the stream as binary stream.
```suggestion
        binary: Whether to return the stream as binary stream.

```

2024-05-17 13:08 UTC, Schamper commented on flow/record/utils.py
> +        binary: Whether to return the stream as binary stream.
```suggestion
        binary: Whether to return the stream as binary stream.

```

2024-05-17 13:08 UTC, Schamper commented on flow/record/utils.py
> +    """Returns True if `fp` is the stdout stream."""
```suggestion
    """Returns True if ``fp`` is the stdout stream."""
```

2024-05-20 15:07 UTC, merged