Be robust against invalid utf-8 byte sequences and surrogateescape them when en- or decoding
fox-it/flow.record pull request #144
Opened 2024-09-30 14:34 UTC by pyrco

This commit also takes the opportunity to remove Python 2 string compatibility code.

It will also remove the final left-over Python 2 compatibility in the test cases.

2024-09-30 15:00 UTC, yunzheng commented
has probably nothing to do with the actual changes in the PR, but i'm not sure why pypy3.9 keep failing.

2024-10-01 08:12 UTC, pyrco commented
> has probably nothing to do with the actual changes in the PR, but i'm not sure why pypy3.9 keep failing in the CI.

There seems to be an issue with a sub-dependency (cramjam) of the avro dependency, which fails building because the installed version of nasm and/or yasm is too old apparently.

Probably a new version got released without wheels for pyp3.9

2024-10-01 08:27 UTC, pyrco commented
> Probably a new version got released without wheels for pypy3.9

Jup, cramjam stopped building wheels for pypy3.9

2024-10-01 10:26 UTC, pyrco commented on flow/record/adapter/sqlite.py
> +                            row[idx] = value.encode()
Yes it should. I had it in there at some point, but it somehow fell-out...

2024-10-01 12:35 UTC, yunzheng requested changes

2024-10-03 06:46 UTC, pyrco commented on flow/record/stream.py
> +        buf = repr(obj).encode(errors="surrogateescape") + b"\n"
It's not needed indeed, `__repr__` should always return a string type, and `repr()` knows how to deal with that if there are surrogates.
I removed it.

2024-10-03 07:07 UTC, yunzheng approved these changes

2024-10-03 07:12 UTC, merged