Make ipnetwork and ipaddress hashable
fox-it/flow.record pull request #148
Opened 2024-10-08 12:05 UTC by Miauwkeru

2024-10-08 12:39 UTC, Schamper submitted a review, later dismissed

2024-10-08 12:39 UTC, Schamper commented on flow/record/fieldtypes/net/ip.py
> +    def __init__(self, addr: Union[str, int]):
```suggestion
    def __init__(self, addr: str | int):
```

2024-10-08 12:39 UTC, Schamper commented on flow/record/fieldtypes/net/ip.py
> +from typing import Union
```suggestion
```

2024-10-08 12:39 UTC, Schamper commented on flow/record/fieldtypes/net/ip.py
> +    def __eq__(self, b: Union[str, int]) -> bool:
```suggestion
    def __eq__(self, b: str | int) -> bool:
```

2024-10-08 12:39 UTC, Schamper commented on flow/record/fieldtypes/net/ip.py
> +    def __init__(self, addr: Union[str, int]):
```suggestion
    def __init__(self, addr: str | int):
```

2024-10-08 12:39 UTC, Schamper commented on flow/record/fieldtypes/net/ip.py
> +    def __eq__(self, b: Union[str, int]) -> bool:
```suggestion
    def __eq__(self, b: str | int) -> bool:
```

2024-10-08 12:39 UTC, Schamper commented on flow/record/fieldtypes/net/ip.py
> +    def __contains__(self, b: Union[str, int, ip_address]) -> bool:
```suggestion
    def __contains__(self, b: str | int | ip_address) -> bool:
```

2024-10-08 12:42 UTC, Schamper commented on flow/record/fieldtypes/net/ip.py
>              raise TypeError("Unable to test subnet containment " "between {} and {}".format(a, b))
Can also f-string this if we're modernizing anyway.

2024-10-08 13:22 UTC, yunzheng requested changes

2024-10-08 13:22 UTC, yunzheng commented on tests/test_fieldtype_ip.py
> +    assert hash(r.subnet) == hash(net.ipnetwork("192.168.0.0/24"))
can you also add a test with set() ?

2024-10-08 15:23 UTC, yunzheng requested changes
can you change to new style typing

2024-10-08 15:23 UTC, yunzheng commented on flow/record/fieldtypes/net/ip.py
> +    def __init__(self, addr: Union[str, int]):
Actually ipaddress can also initialize from 4 bytes, and can you change it to new style typing? eg: `str | int | bytes`

https://docs.python.org/3/library/ipaddress.html#ipaddress.IPv4Address

2024-10-09 10:32 UTC, yunzheng commented
> > can you change to new style typing
> 
> it will break the python3.8 compatibility if I change it to new style typing, which is why i haven't done so.

should work fine due to `from __future__ import annotations`

2024-10-09 11:37 UTC, yunzheng requested changes
some small suggestions and then it should be good to go!

2024-10-09 11:37 UTC, yunzheng commented on flow/record/fieldtypes/net/ip.py
> +    def __eq__(self, b: str | int | bytes) -> bool:
```suggestion
    def __eq__(self, b: str | int | bytes | _IPAddress) -> bool:
```

2024-10-09 11:37 UTC, yunzheng commented on flow/record/fieldtypes/net/ip.py
> +    def __eq__(self, b: str | int | bytes) -> bool:
```suggestion
    def __eq__(self, b: str | int | bytes | _IPNetwork) -> bool:
```

2024-10-09 11:47 UTC, yunzheng approved these changes

2024-10-09 11:50 UTC, merged