Don't output RecordDescriptor information in JSON output of `rdump`
fox-it/flow.record pull request #23
Opened 2022-11-04 17:19 UTC by yunzheng

This disables outputting recorddescriptor information in the JSON output when using `--json` or `--jsonlines` as this is rarely what you want as an end user.

It's still possible to output recorddescriptor information if you use `jsonfile://<file>?descriptors=true` as the adapter.

(DIS-1637)

2022-11-04 17:28 UTC, Schamper requested changes

2022-11-04 17:28 UTC, Schamper commented on flow/record/adapter/jsonfile.py
> +Write usage: rdump -w jsonfile://[PATH]?indent=[INDENT]&?descriptors=[DESCRIPTORS]
```suggestion
Write usage: rdump -w jsonfile://[PATH]?indent=[INDENT]&descriptors=[DESCRIPTORS]
```

2022-11-04 17:28 UTC, Schamper commented on tests/test_rdump.py
> +                    subnet="192.168.{}.0/24".format(i),
```suggestion
                    ip=f"172.16.0.{i}",
                    subnet=f"192.168.{i}.0/24",
```

2022-11-04 17:28 UTC, Schamper commented on tests/test_rdump.py
> +        assert json_dict["subnet"] == "192.168.{}.0/24".format(i)
```suggestion
        assert json_dict["ip"] == f"172.16.0.{i}"
        assert json_dict["subnet"] == f"192.168.{i}.0/24"
```

2022-11-04 19:03 UTC, Schamper approved these changes

2022-11-04 20:29 UTC, merged

2023-01-02 18:33 UTC, Zawadidone commented
@yunzheng should usage of `jsonfile://<file>` output the record descriptor? I would have not expected that because the parameter `?descriptors=True` is not specified.

```bash
target-query -t targets/* -f appinit -q | rdump -w jsonfile://test1.jsonl
[reading from stdin]
root@processing-anti:/mnt/processing# head -n 1 test1.jsonl 
{"_type": "recorddescriptor", "_data": ["filesystem/registry/appinit", [["string", "hostname"], ["string", "domain"], ["datetime", "ts"], ["uri", "path"], ["string", "regf_hive_path"], ["string", "regf_key_path"], ["string", "username"], ["string", "user_id"], ["string", "user_home"]]]}
```

2023-01-03 00:22 UTC, Schamper commented
@Zawadidone looks like `True` is the default value, so specifying `False` will actually get the behavior you're looking for.

2023-01-09 13:11 UTC, yunzheng commented
@Zawadidone I left the default to `True` for the record adapter itself, as I was not sure if it would introduce breaking changes to other plugins that might use the JSON adapter. It's only set to `False` in the `rdump` tool when using the `--json` or `--jsonlines` flags, you could use output redirection instead of using the `jsonfile://` uri:

```shell
target-query -t targets/* -f appinit -q | rdump -J > test1.jsonl
```

Let us know if you think this behaviour should be changed.

2023-01-09 13:23 UTC, Zawadidone commented
It works great. This makes it possible to dynamicly ingest rdump JSON files to Elasticsearch/Timesketch.